// Dummy products data for demo
export const dummyProducts = [
  // Elite Sports Products (6 products)
  {
    id: 1,
    name: 'Pro Football Cleats',
    brand: 'Elite Sports',
    price: 12999,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    category: 'Footwear',
    description: 'Premium football cleats designed for professional athletes',
    rating: 4.8,
    reviews: 245,
  },
  {
    id: 2,
    name: 'Elite Sports Training Shorts',
    brand: 'Elite Sports',
    price: 1899,
    image: 'https://images.unsplash.com/photo-1506629082632-401ba2df15fa?w=500&h=500&fit=crop',
    category: 'Apparel',
    description: 'High-performance training shorts with moisture-wicking technology',
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 3,
    name: 'Elite Sports Performance Socks',
    brand: 'Elite Sports',
    price: 599,
    image: 'https://images.unsplash.com/photo-1539148763612-d1b1b3b3b3b3?w=500&h=500&fit=crop',
    category: 'Apparel',
    description: 'Comfortable sports socks with arch support',
    rating: 4.6,
    reviews: 189,
  },
  {
    id: 4,
    name: 'Elite Sports Training Belt',
    brand: 'Elite Sports',
    price: 2499,
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500&h=500&fit=crop',
    category: 'Equipment',
    description: 'Heavy-duty weight training belt with superior support',
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 5,
    name: 'Elite Sports Gym Bag',
    brand: 'Elite Sports',
    price: 3499,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
    category: 'Accessories',
    description: 'Spacious gym bag with multiple compartments',
    rating: 4.5,
    reviews: 167,
  },
  {
    id: 6,
    name: 'Elite Sports Water Bottle',
    brand: 'Elite Sports',
    price: 1299,
    image: 'https://images.unsplash.com/photo-1523438097915-512252fce853?w=500&h=500&fit=crop',
    category: 'Accessories',
    description: 'Insulated water bottle keeping drinks cold for 24 hours',
    rating: 4.7,
    reviews: 312,
  },

  // Court Kings Products (5 products)
  {
    id: 7,
    name: 'Basketball Jersey Set',
    brand: 'Court Kings',
    price: 3499,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    category: 'Apparel',
    description: 'Breathable basketball jersey with advanced moisture-wicking technology',
    rating: 4.6,
    reviews: 178,
  },
  {
    id: 8,
    name: 'Court Kings Basketball Shorts',
    brand: 'Court Kings',
    price: 2299,
    image: 'https://images.unsplash.com/photo-1506629082632-401ba2df15fa?w=500&h=500&fit=crop',
    category: 'Apparel',
    description: 'Premium basketball shorts with deep pockets',
    rating: 4.7,
    reviews: 145,
  },
  {
    id: 9,
    name: 'Court Kings Basketball Shoes',
    brand: 'Court Kings',
    price: 8999,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    category: 'Footwear',
    description: 'Professional basketball shoes with ankle support',
    rating: 4.9,
    reviews: 267,
  },
  {
    id: 10,
    name: 'Court Kings Headband Set',
    brand: 'Court Kings',
    price: 899,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&h=500&fit=crop',
    category: 'Accessories',
    description: 'Sweat-absorbent headbands for basketball players',
    rating: 4.5,
    reviews: 98,
  },
  {
    id: 11,
    name: 'Court Kings Sports Towel',
    brand: 'Court Kings',
    price: 599,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=500&fit=crop',
    category: 'Accessories',
    description: 'Quick-dry microfiber sports towel',
    rating: 4.6,
    reviews: 201,
  },

  // Active Gear Products (4 products)
  {
    id: 12,
    name: 'Running Watch Pro',
    brand: 'Active Gear',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
    category: 'Accessories',
    description: 'Advanced sports watch with GPS and heart rate monitoring',
    rating: 4.9,
    reviews: 392,
  },
  {
    id: 13,
    name: 'Active Gear Running Shoes',
    brand: 'Active Gear',
    price: 7999,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    category: 'Footwear',
    description: 'Lightweight running shoes with cushioned sole',
    rating: 4.8,
    reviews: 298,
  },
  {
    id: 14,
    name: 'Active Gear Fitness Tracker',
    brand: 'Active Gear',
    price: 4999,
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500&h=500&fit=crop',
    category: 'Accessories',
    description: 'Advanced fitness tracker with sleep monitoring',
    rating: 4.7,
    reviews: 342,
  },
  {
    id: 15,
    name: 'Active Gear Sports Armband',
    brand: 'Active Gear',
    price: 1499,
    image: 'https://images.unsplash.com/photo-1523438097915-512252fce853?w=500&h=500&fit=crop',
    category: 'Accessories',
    description: 'Secure armband for phone with reflective strip',
    rating: 4.6,
    reviews: 234,
  },
];

export const dummyOrders = [
  // Elite Sports Orders (orders from Elite Sports products)
  {
    id: 'ORD-001',
    brand: 'Elite Sports',
    customer: 'Rajesh Kumar',
    product: 'Pro Football Cleats',
    amount: 12999,
    status: 'Delivered',
    date: '2026-03-28',
  },
  {
    id: 'ORD-002',
    brand: 'Elite Sports',
    customer: 'Priya Singh',
    product: 'Running Watch Pro',
    amount: 24999,
    status: 'Processing',
    date: '2026-04-01',
  },
  {
    id: 'ORD-006',
    brand: 'Elite Sports',
    customer: 'Anjali Verma',
    product: 'Training Shorts',
    amount: 1899,
    status: 'Delivered',
    date: '2026-03-20',
  },

  // Court Kings Orders (orders from Court Kings products)
  {
    id: 'ORD-003',
    brand: 'Court Kings',
    customer: 'Arjun Patel',
    product: 'Basketball Jersey Set',
    amount: 3499,
    status: 'Shipped',
    date: '2026-03-30',
  },
  {
    id: 'ORD-007',
    brand: 'Court Kings',
    customer: 'Karan Singh',
    product: 'Basketball Shoes',
    amount: 8999,
    status: 'Processing',
    date: '2026-04-02',
  },

  // Active Gear Orders (orders from Active Gear products)
  {
    id: 'ORD-004',
    brand: 'Active Gear',
    customer: 'Neha Sharma',
    product: 'Yoga Mat Premium',
    amount: 3999,
    status: 'Delivered',
    date: '2026-03-25',
  },
  {
    id: 'ORD-005',
    brand: 'Active Gear',
    customer: 'Vikram Joshi',
    product: 'Cricket Bat Professional',
    amount: 8999,
    status: 'Processing',
    date: '2026-04-02',
  },
];

export const dummyAnalytics = {
  totalSales: 247850,
  totalOrders: 89,
  totalProducts: 15,
  totalRevenue: 847500,
  averageOrderValue: 9528,
  conversionRate: 3.8,
  topProduct: 'Running Watch Pro',
  topCategory: 'Accessories',
};

export const categories = [
  'All',
  'Footwear',
  'Apparel',
  'Accessories',
  'Equipment',
  'Sports Equipment',
  'Safety Gear',
];
